github:
  client:
    id: a9e8cdb105d994813b0e
    secret: 7d9bc181b2f3421ea049d6c9d9d56caec30712b5
  redirect:
    uri: http://localhost:8080/callback
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8