github:
  client:
    id: a9e8cdb105d994813b0e
    secret: 8e4c6c32f3d8fa399f19d8190980b733df35ea50
  redirect:
    uri: http://localhost:8080/callback
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
mybatis:
  configuration:
    setmapUnderscoreToCamelCase: true
