github:
  client:
    id: a9e8cdb105d994813b0e
    secret: da7709fc4f8123f564f86a25a736802f2799eb8b
  redirect:
    uri: http://localhost:8080/callback
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
mybatis:
  configuration:
    setmapUnderscoreToCamelCase: true
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.xm.community.community.model
  mapper-locations: classpath:com.xm.community.community.mapper/*.xml
